apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: akmebank
  namespace: argocd 
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-manifest-bundles'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/gajananan/interlace-manifests
        targetRevision: main
        path: manifest-bundles/{{name}}
      destination:
        server: '{{server}}'
        namespace: bundle-manifests