apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-interlace-controller
  namespace: argocd-interlace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-interlace-controller
  template:
    metadata:
      labels:
        app: argocd-interlace-controller
    spec:
      serviceAccountName: argocd-interlace-controller
      containers:
        - name: argocd-interlace-controller
          image: gcr.io/signing-demo-project/argocd-interlace-controller:dev5
          imagePullPolicy: Always
          command:
            - argocd-interlace
          args:
            - --namespace=argocd  
          env:
            - name: ARGOCD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-token-secret
                  key: ARGOCD_TOKEN            
          #volumeMounts:
          #  - name: signing-secrets
          #    mountPath: /etc/signing-secrets

      #volumes:
       # - name: signing-secrets
        #  secret:
         #   secretName: signing-secrets