- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: DOCKER_CONFIG
      value: /tmp/.docker/
    - name: MANIFEST_STORAGE_TYPE
      value: oci #/git/oci
    - name: OCI_IMAGE_REGISTRY
      value: gcr.io/<some-registry-name>
    - name: OCI_IMAGE_PREFIX
      value: "argocd.apps"
    - name: OCI_IMAGE_TAG
      value: "mnf"        
    - name: REKOR_SERVER
      value: https://rekor.sigstore.dev
    - name: COSIGN_PASSWORD
      value: ""
    - name: MANIFEST_ARGOCD_PROJECT
      value: default
    - name: MANIFEST_GITREPO_URL  
      valueFrom:
        secretKeyRef:
          name: interlace-manifest-git-secret
          key: MANIFEST_GITREPO_URL
    - name: MANIFEST_GITREPO_SUFFIX
      valueFrom:
        secretKeyRef:
          name: interlace-manifest-git-secret
          key: MANIFEST_GITREPO_SUFFIX
    - name: MANIFEST_GITREPO_BRANCH
      valueFrom:
        secretKeyRef:
          name: interlace-manifest-git-secret
          key: MANIFEST_GITREPO_BRANCH
    - name: MANIFEST_GITREPO_TOKEN
      valueFrom:
        secretKeyRef:
          name: interlace-manifest-git-secret
          key: MANIFEST_GITREPO_TOKEN
    - name: MANIFEST_GITREPO_USER
      valueFrom:
        secretKeyRef:
          name: interlace-manifest-git-secret
          key: MANIFEST_GITREPO_USER
    - name: MANIFEST_GITREPO_USEREMAIL
      valueFrom:
        secretKeyRef:
          name: interlace-manifest-git-secret
          key: MANIFEST_GITREPO_USEREMAIL
    - name: MANIFEST_DEST_NAMESPACE
      valueFrom:
        secretKeyRef:
          name: interlace-manifest-git-secret
          key: MANIFEST_DEST_NAMESPACE
    - name: MANIFEST_GITREPO_MODE
      valueFrom:
        secretKeyRef:
          name: interlace-manifest-git-secret
          key: MANIFEST_GITREPO_MODE
    - name: K8S_MANIFEST_SIGSTORE_LOG_LEVEL
      value: info
    - name: ARGOCD_INTERLACE_LOG_LEVEL
      value: info
    - name: "ARGOCD_NAMESPACE"  
      valueFrom:
        secretKeyRef:
          name: argocd-token-secret
          key: ARGOCD_NAMESPACE
    - name: ARGOCD_API_BASE_URL
      valueFrom:
        secretKeyRef:
          name: argocd-token-secret
          key: ARGOCD_API_BASE_URL
    - name: ARGOCD_TOKEN
      valueFrom:
        secretKeyRef:
          name: argocd-token-secret
          key: ARGOCD_TOKEN