apiVersion: v1
kind: Secret
metadata:
    name: signing-secrets
    namespace: argocd-interlace
type: Opaque    
#data:
#   cosign.key:
#   cosign.password:

---
apiVersion: v1
kind: Secret
metadata:
    name: argocd-interlace-gcr-secret
    namespace: argocd-interlace
type: Opaque    
#data:
#   .dockerconfigjson:

---
apiVersion: v1
kind: Secret
metadata:
    name: argocd-token-secret
    namespace: argocd-interlace
type: Opaque    
data:
   ARGOCD_API_BASE_URL: UkVQTEFDRSBUSElTCg==
   ARGOCD_NAMESPACE: UkVQTEFDRSBUSElTCg==
   ARGOCD_TOKEN: UkVQTEFDRSBUSElTCg==