apiVersion: v1
kind: Secret
metadata:
    name: signing-secrets
    namespace: argocd-interlace
type: Opaque    
data:
   cosign.key: UkVQTEFDRSBUSElTCg==
   cosign.pub: UkVQTEFDRSBUSElTCg==

---
apiVersion: v1
kind: Secret
metadata:
    name: argocd-interlace-gcr-secret
    namespace: argocd-interlace
type: Opaque    
data:
   .dockerconfigjson: UkVQTEFDRSBUSElTCg==

---
apiVersion: v1
kind: Secret
metadata:
    name: argocd-token-secret
    namespace: argocd-interlace
type: Opaque    
data:
   ARGOCD_API_BASE_URL: UkVQTEFDRSBUSElTCg==
   ARGOCD_NAMESPACE: YXJnb2NkCg==
   ARGOCD_TOKEN: UkVQTEFDRSBUSElTCg==

---
apiVersion: v1
kind: Secret
metadata:
    name: interlace-manifest-git-secret
    namespace: argocd-interlace
type: Opaque
data:
    MANIFEST_GITREPO_URL: UkVQTEFDRSBUSElTCg==
    MANIFEST_GITREPO_BRANCH: UkVQTEFDRSBUSElTCg==
    MANIFEST_GITREPO_TOKEN: UkVQTEFDRSBUSElTCg==
    MANIFEST_GITREPO_USER: UkVQTEFDRSBUSElTCg==
    MANIFEST_GITREPO_USEREMAIL: UkVQTEFDRSBUSElTCg==
    MANIFEST_DEST_NAMESPACE: UkVQTEFDRSBUSElTCg==
    MANIFEST_GITREPO_SUFFIX: UkVQTEFDRSBUSElTCg==
    MANIFEST_GITREPO_MODE: UkVQTEFDRSBUSElTCg==