apiVersion: v1
kind: Namespace
metadata:
  name: argocd-interlace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-interlace-controller
  namespace: argocd-interlace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-interlace-controller-tenant-access
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-interlace-controller-tenant-access
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-interlace-controller-tenant-access
subjects:
- kind: ServiceAccount
  name: argocd-interlace-controller
  namespace: argocd-interlace
---
apiVersion: v1
data:
  .dockerconfigjson: UkVQTEFDRSBUSElTCg==
kind: Secret
metadata:
  name: argocd-interlace-gcr-secret
  namespace: argocd-interlace
type: Opaque
---
apiVersion: v1
data:
  ARGOCD_API_BASE_URL: UkVQTEFDRSBUSElTCg==
  ARGOCD_NAMESPACE: YXJnb2NkCg==
  ARGOCD_TOKEN: UkVQTEFDRSBUSElTCg==
kind: Secret
metadata:
  name: argocd-token-secret
  namespace: argocd-interlace
type: Opaque
---
apiVersion: v1
data:
  MANIFEST_DEST_NAMESPACE: UkVQTEFDRSBUSElTCg==
  MANIFEST_GITREPO_BRANCH: UkVQTEFDRSBUSElTCg==
  MANIFEST_GITREPO_MODE: UkVQTEFDRSBUSElTCg==
  MANIFEST_GITREPO_SUFFIX: UkVQTEFDRSBUSElTCg==
  MANIFEST_GITREPO_TOKEN: UkVQTEFDRSBUSElTCg==
  MANIFEST_GITREPO_URL: UkVQTEFDRSBUSElTCg==
  MANIFEST_GITREPO_USER: UkVQTEFDRSBUSElTCg==
  MANIFEST_GITREPO_USEREMAIL: UkVQTEFDRSBUSElTCg==
kind: Secret
metadata:
  name: interlace-manifest-git-secret
  namespace: argocd-interlace
type: Opaque
---
apiVersion: v1
data:
  cosign.key: UkVQTEFDRSBUSElTCg==
  cosign.pub: UkVQTEFDRSBUSElTCg==
kind: Secret
metadata:
  name: signing-secrets
  namespace: argocd-interlace
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-interlace-controller
  namespace: argocd-interlace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-interlace-controller
  template:
    metadata:
      labels:
        app: argocd-interlace-controller
    spec:
      containers:
      - args:
        - --namespace=argocd
        command:
        - argocd-interlace
        env:
        - name: DOCKER_CONFIG
          value: /tmp/.docker/
        - name: MANIFEST_STORAGE_TYPE
          value: oci
        - name: OCI_IMAGE_REGISTRY
          value: gcr.io/<some-registry-name>
        - name: OCI_IMAGE_PREFIX
          value: argocd.apps
        - name: OCI_IMAGE_TAG
          value: mnf
        - name: REKOR_SERVER
          value: https://rekor.sigstore.dev
        - name: COSIGN_PASSWORD
          value: ""
        - name: MANIFEST_ARGOCD_PROJECT
          value: default
        - name: MANIFEST_GITREPO_URL
          valueFrom:
            secretKeyRef:
              key: MANIFEST_GITREPO_URL
              name: interlace-manifest-git-secret
        - name: MANIFEST_GITREPO_SUFFIX
          valueFrom:
            secretKeyRef:
              key: MANIFEST_GITREPO_SUFFIX
              name: interlace-manifest-git-secret
        - name: MANIFEST_GITREPO_BRANCH
          valueFrom:
            secretKeyRef:
              key: MANIFEST_GITREPO_BRANCH
              name: interlace-manifest-git-secret
        - name: MANIFEST_GITREPO_TOKEN
          valueFrom:
            secretKeyRef:
              key: MANIFEST_GITREPO_TOKEN
              name: interlace-manifest-git-secret
        - name: MANIFEST_GITREPO_USER
          valueFrom:
            secretKeyRef:
              key: MANIFEST_GITREPO_USER
              name: interlace-manifest-git-secret
        - name: MANIFEST_GITREPO_USEREMAIL
          valueFrom:
            secretKeyRef:
              key: MANIFEST_GITREPO_USEREMAIL
              name: interlace-manifest-git-secret
        - name: MANIFEST_DEST_NAMESPACE
          valueFrom:
            secretKeyRef:
              key: MANIFEST_DEST_NAMESPACE
              name: interlace-manifest-git-secret
        - name: MANIFEST_GITREPO_MODE
          valueFrom:
            secretKeyRef:
              key: MANIFEST_GITREPO_MODE
              name: interlace-manifest-git-secret
        - name: K8S_MANIFEST_SIGSTORE_LOG_LEVEL
          value: info
        - name: ARGOCD_INTERLACE_LOG_LEVEL
          value: info
        - name: ARGOCD_NAMESPACE
          valueFrom:
            secretKeyRef:
              key: ARGOCD_NAMESPACE
              name: argocd-token-secret
        - name: ARGOCD_API_BASE_URL
          valueFrom:
            secretKeyRef:
              key: ARGOCD_API_BASE_URL
              name: argocd-token-secret
        - name: ARGOCD_TOKEN
          valueFrom:
            secretKeyRef:
              key: ARGOCD_TOKEN
              name: argocd-token-secret
        image: gcr.io/kg-image-registry/argocd-interlace-controller:dev
        imagePullPolicy: Always
        name: argocd-interlace-controller
        volumeMounts:
        - mountPath: /tmp/output
          name: output
        - mountPath: /etc/signing-secrets
          name: signing-secrets
        - mountPath: /tmp/.docker/
          name: gcr-registry-docker-config
      serviceAccountName: argocd-interlace-controller
      volumes:
      - name: signing-secrets
        secret:
          secretName: signing-secrets
      - emptyDir: {}
        name: output
      - name: gcr-registry-docker-config
        secret:
          items:
          - key: .dockerconfigjson
            path: config.json
          secretName: argocd-interlace-gcr-secret
